steps:
  # Reservations
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'europe-central2-docker.pkg.dev/sleepr-421612/reservations/production',
      '-f',
      'apps/reservations/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-central2-docker.pkg.dev/sleepr-421612/reservations/production'
    ]

  # Notifications
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'europe-central2-docker.pkg.dev/sleepr-421612/notifications/production',
      '-f',
      'apps/notifications/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-central2-docker.pkg.dev/sleepr-421612/notifications/production'
    ]

  # Payments
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'europe-central2-docker.pkg.dev/sleepr-421612/payments/production',
      '-f',
      'apps/payments/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-central2-docker.pkg.dev/sleepr-421612/payments/production'
    ]

  # Auth
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'europe-central2-docker.pkg.dev/sleepr-421612/auth/production',
      '-f',
      'apps/auth/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-central2-docker.pkg.dev/sleepr-421612/auth/production'
    ]