services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    image: europe-central2-docker.pkg.dev/sleepr-421612/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3001:3001'
  auth:
    image: europe-central2-docker.pkg.dev/sleepr-421612/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3002:3002'
  payments:
    image: europe-central2-docker.pkg.dev/sleepr-421612/payments/production
    env_file:
      - ../apps/payments/.env
    ports:
      - '3004:3004'
  notifications:
    image: europe-central2-docker.pkg.dev/sleepr-421612/notifications/production
    env_file:
      - ../apps/notifications/.env
    ports:
      - '3005:3005'
  mongo:
    image: mongo